trigger:
  branches:
    include:
    - main
    - feature/*
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - main

jobs:
- template: templates/build-process.yml
  parameters:
    vmImage: 'ubuntu-latest'
    service_connection_nuget_org: ''
    service_connection_github: ''
    netSdkVersion: '6.x'
